name: rna-seq-reporting

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - pip
